package io.github.timortel.kotlin_multiplatform_grpc_plugin.generate_mulitplatform_sources.generators.protofile

import io.github.timortel.kotlin_multiplatform_grpc_plugin.generate_mulitplatform_sources.generators.protofile.enumeration.CommonProtoEnumerationWriter
import io.github.timortel.kotlin_multiplatform_grpc_plugin.generate_mulitplatform_sources.generators.protofile.enumeration.ProtoEnumerationWriter
import io.github.timortel.kotlin_multiplatform_grpc_plugin.generate_mulitplatform_sources.generators.protofile.message.CommonProtoMessageWriter
import io.github.timortel.kotlin_multiplatform_grpc_plugin.generate_mulitplatform_sources.generators.protofile.message.ProtoMessageWriter
import io.github.timortel.kotlin_multiplatform_grpc_plugin.generate_mulitplatform_sources.generators.service.CommonProtoServiceWriter
import io.github.timortel.kotlin_multiplatform_grpc_plugin.generate_mulitplatform_sources.generators.service.ProtoServiceWriter

object CommonProtoFileWriter : ProtoFileWriter(isActual = false) {
    override val protoServiceWriter: ProtoServiceWriter = CommonProtoServiceWriter
    override val protoMessageWriter: ProtoMessageWriter = CommonProtoMessageWriter
    override val protoEnumWriter: ProtoEnumerationWriter = CommonProtoEnumerationWriter
}
