services:
  envoy:
    image: envoyproxy/envoy-dev:latest
    volumes:
      - ./envoy.yml:/etc/envoy/envoy.yaml
    network_mode: "host"
    ports:
      - "8082:8082"

  js-test:
    image: kmp-grpc-jstest
    build:
      context: ..
    network_mode: "host"
    depends_on:
      envoy:
        condition: service_started
      test-server:
        condition: service_started
    command:
      - grpc-mp-test:jsTest
    volumes:
      - ./test-outputs/:/tests/grpc-mp-test/build/reports/tests

  test-server:
    image: kmp-grpc-testserver
    build:
      context: ..
    network_mode: "host"
    ports:
      - "17888:17888"
    command:
      - buildSrc:test-server:run
