[package]
name = "kmp-grpc-native-rust"
version = "0.1.0"
edition = "2024"

[dependencies]
tonic = { version = "0.13.0", features = ["transport"] }
tokio = { version = "1.44.2", features = ["rt-multi-thread", "macros"] }
bytes = "1.10.1"
once_cell = "1.21.3"

[lib]
crate-type = ["staticlib"]
