package io.github.timortel.kmpgrpc.core.message

/**
 * Base interface for all grpc messages. All messages are automatically generated by the gradle plugin based on your proto definitions.
 */
expect interface KMMessage {

    /**
     * The name of this proto: <proto-package>.<name>
     */
    val fullName: String

    open fun serialize(): ByteArray
}
