package io.github.timortel.kmpgrpc.core.message

/**
 * Base interface for all grpc messages. All messages are automatically generated by the gradle plugin based on your proto definitions.
 */
expect interface KMMessage
