package io.github.timortel.kmpgrpc.core.message

import io.github.timortel.kmpgrpc.core.io.CodedOutputStream

/**
 * Base interface for all grpc messages. All messages are automatically generated by the gradle plugin based on your proto definitions.
 */
expect interface Message {

    /**
     * The size this message takes up in a byte array.
     */
    val requiredSize: Int

    /**
     * The name of this proto: <proto-package>.<name>
     */
    val fullName: String

    /**
     * If all required fields for this message have been set.
     */
    val isInitialized: Boolean

    /**
     * Serializes this message and returns it as a [ByteArray].
     *
     * @return A byte array containing the serialized representation of this message.
     */
    open fun serialize(): ByteArray

    /**
     * Serializes this message and writes it directly to the specified [CodedOutputStream].
     *
     * @param stream The [CodedOutputStream] instance to which the serialized message will be written.
     */
    fun serialize(stream: CodedOutputStream)
}
