name: Serialization and RPC tests.

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  test-jvm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Start test-server
        run: docker compose -f docker-tests/js-tests.yml up -d test-server

      - name: Run tests in plugin module
        run: ./gradlew :grpc-mp-test:jvmTest

      - name: Stop docker services
        run: docker compose -f docker-tests/js-tests.yml down
        if: always()

  test-js:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Start envoy And test-server
        run: docker compose -f docker-tests/js-tests.yml up -d envoy test-server

      - name: Run tests in plugin module
        run: ./gradlew :grpc-mp-test:jsTest

      - name: Stop docker services
        run: docker compose -f docker-tests/js-tests.yml down
        if: always()

  test-ios:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Start test-server
        run: docker compose -f docker-tests/js-tests.yml up -d test-server

      - name: Run tests in plugin module
        run: ./gradlew :grpc-mp-test:iosSimulatorArm64Test

      - name: Stop docker services
        run: docker compose -f docker-tests/js-tests.yml down
        if: always()